server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import: classpath:application-common.yml
  datasource:
    url: jdbc:postgresql://localhost:5434/orderdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

logging:
  level:
    com.ecommerce.order: DEBUG
    org.springframework.web: INFO
    org.springframework.cloud.openfeign: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Swagger Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    persist-authorization: true
  packages-to-scan: com.ecommerce.order
  paths-to-match: /api/**

swagger:
  api:
    title: Order Service API
    description: API Documentation for Order Management Service
    version: 1.0.0
    contact:
      name: Development Team
      email: dev@ecommerce.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true
    db:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orderdb

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/