# Common configuration for all microservices
# Redis Configuration
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1000ms
        retryExceptions:
          - java.io.IOException
  timelimiter:
    instances:
      default:
        timeoutDuration: 3s

---
# Docker profile overrides
spring:
  config:
    activate:
      on-profile: docker
  redis:
    host: redis
    port: 6379